# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

source ~/dotfiles/functions
source ~/dotfiles/aliases

# Add homebrew to the completion path
fpath=("/usr/local/bin/" $fpath)

# This makes cd=pushd
setopt AUTO_PUSHD

# If we have a glob this will expand it
setopt GLOB_COMPLETE
setopt PUSHD_MINUS

# blank pushd goes to home
setopt PUSHD_TO_HOME

# this will ignore multiple directories for the stack.  Useful?  I dunno.
setopt PUSHD_IGNORE_DUPS


setopt APPEND_HISTORY
HISTSIZE=5200
SAVEHIST=5000
setopt EXTENDED_HISTORY
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS

unsetopt correct

export EDITOR="subl -n -w"

if which rbenv > /dev/null; then eval "$(rbenv init - zsh)"; fi
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
